# Generated by Django 4.2.23 on 2025-08-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'release_date')},
        ),
    ]
