# Generated by Django 4.2.23 on 2025-08-25 11:13

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
