# Generated by Django 4.2.23 on 2025-08-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ai_prompts', '0002_prompt_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='response',
        ),
    ]
