# Generated by Django 4.2.23 on 2025-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ai_prompts', '0003_remove_prompt_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
